[package]
name = "udpprox"
version = "0.1.1"
authors = ["cake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
hex-slice = "0.1.4"
pnet = "0.27.2"
rand = "0.8.0"
getopts = "0.2.21"
